name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.1)'
        required: true
        type: string

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: |
          cd source
          npm ci
      
      - name: Run tests
        run: |
          cd source
          npm test
      
      - name: Build project
        run: |
          ./build.sh
      
      - name: Set version (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        run: |
          cd package
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
      
      - name: Create tarball
        run: |
          cd package
          npm pack
          mv *.tgz ../backlog-md-mcp.tgz
      
      - name: Publish to npm
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          cd package
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            backlog-md-mcp.tgz
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}